---
- name: Update Ubuntu 22.04
  hosts: ubuntu22
  become: true
#  become_user: root [Esta línea indica al usuario root - preguntar a Paco]
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Autoremove packages
      apt:
        autoremove: yes
