---
# Instalación clamAV
#
- name: Actualizar caché de paquetes
  apt:
    update_cache: yes

- name: Instalar ClamAV
  apt:
    name: clamav
    state: present

- name: Crear archivo de configuración clamd si no existe
  file:
    path: /etc/clamav/clamd.conf
    state: touch

- name: Configurar ClamAV
  lineinfile:
    path: /etc/clamav/clamd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^Example", line: "Example false" }
    - { regexp: "^LocalSocket", line: "LocalSocket /var/run/clamav/clamd.ctl" }
    - { regexp: "^FixStaleSocket", line: "FixStaleSocket true" }
    - { regexp: "^TCPSocket", line: "TCPSocket 3310" }
    - { regexp: "^TCPAddr", line: "TCPAddr 127.0.0.1" }
    - { regexp: "^MaxScanSize", line: "MaxScanSize 100M" }
    - { regexp: "^MaxFileSize", line: "MaxFileSize 100M" }
    - { regexp: "^MaxRecursion", line: "MaxRecursion 16" }
    - { regexp: "^MaxDirectoryRecursion", line: "MaxDirectoryRecursion 8" }
